<?php
/**
 * @file Provides VoIP Drupal functionality for the PPH project
 */

foreach (array('pph.scripts.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . $file);
}

/**
 * Implementation of hook_perm().
 */
function pph_perm() {
  return array('administer pph');
}

/*
 * Implementation of hook_menu()
 */
function pph_menu() {
  $items = array();

  $items['admin/settings/pph'] = array(
    'title' => 'PPH',
    'description' => 'PPH configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pph_admin_form', NULL),
    'access arguments' => array('administer pph'),
  );

  return $items;
}

function pph_admin_form($configuration) {
  $form['pph_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Contact email'),
    '#description' => t("The email address(es) to send the information requests to. If empty, no email messages will be sent."),
    '#default_value' => variable_get('pph_email', ''),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

function pph_admin_form_submit($form, &$form_state) {
  if ($form_state['values']['pph_email']) {
    drupal_set_message(t('Contact email updated.'));
    $email = trim($form_state['values']['pph_email']);
    variable_set('pph_email', $email);
  }
}


